# Generated by Django 4.2.1 on 2023-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.TextField(max_length=255)),
                ('nome_fantasia', models.TextField(max_length=255)),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.TextField(max_length=11)),
                ('email', models.EmailField(max_length=255)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero_logradouro', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
    ]
