# Generated by Django 4.2.1 on 2023-05-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_fornecedor_produto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.TextField(max_length=80),
        ),
    ]
