# Generated by Django 4.2.1 on 2023-05-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_alter_fornecedor_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
    ]
